### ISSUE TITLE
AttributeError: 'TensorBoardColabCallback' object has no attribute 'is_eager_execution'

### ISSUE THREAD

**Issue by simpleParadox** [taomanwai/tensorboardcolab#6]
The callbacks parameter for Keras is not taking inputs for TensorBoardColabCallback. @taomanwai 
[https://colab.research.google.com/drive/19_QqEfi8WeNkbhRpxObukE8IggmMFJWY#scrollTo=UwtUJEjI51en](url)

Please have a look or suggest a temporary solution.

**Comment by taomanwai** [comment]
Just fixed. Sorry for inconvenience caused

Please install latest version again by:

pip install -U tensorboardcolab

**Comment by mrcmoresi** [comment]
Dear @taomanwai i have the same issue but i cant fix it upgrading the package, here is the problem with the callbacks

[Colab Notebook](https://colab.research.google.com/drive/1irSF4KVttsEnbNwSN-cOx46TUp2nvsW4)

**Comment by simpleParadox** [comment]
Hello, the issue has still not been fixed. The error till exists.

**Comment by taomanwai** [comment]
Well received

Will fix it ASAP

**Comment by mariomeissner** [comment]
Can confirm, I also have the same issue even after installing 0.0.21.

**Comment by taomanwai** [comment]
0.0.22 is available, & fully tested!

To ensure upgrade succeed, please:
1. Restart colab server (to clear any cache mechanism)
2. pip install -U tensorboardcolab

**Comment by mariomeissner** [comment]
Thank you, it works now! 😁

**Comment by chanckjoseph** [comment]
Applied !pip install -U tensorboardcolab.  Still getting AttributeError: 'TensorBoardColabCallback' object has no attribute 'on_train_batch_begin'

**Comment by yejilee-herings** [comment]
> Applied !pip install -U tensorboardcolab. Still getting AttributeError: 'TensorBoardColabCallback' object has no attribute 'on_train_batch_begin'

I am also getting the same error message.

**Comment by virtualdvid** [comment]
I got the same error even using `!pip install -U --ignore-installed tensorboardcolab`

**Comment by paweljedrzejewski** [comment]
I have the same issue. Do you guys know is there any way of using Tensor Board with Google Colab as a workaround?

**Comment by virtualdvid** [comment]
There is an alternative solution but we have to use TFv2.0 preview. So if you don't have problems with the migration try this: 

install tfv2.0 for GPU or CPU (TPU no available yet)

CPU
tf-nightly-2.0-preview
GPU
tf-nightly-gpu-2.0-preview

```
%%capture
!pip install -q tf-nightly-gpu-2.0-preview
# Load the TensorBoard notebook extension
%load_ext tensorboard.notebook
```
import TensorBoard as usual:

`from tensorflow.keras.callbacks import TensorBoard`

Clean or Create folder where to save the logs (run this lines before run the training `fit()`)

```
# Clear any logs from previous runs
import time

!rm -R ./logs/ # rf
log_dir="logs/fit/{}".format(time.strftime("%Y%m%d-%H%M%S", time.gmtime()))
tensorboard = TensorBoard(log_dir=log_dir, histogram_freq=1)
```
Have fun with TensorBoard! :)

`%tensorboard --logdir logs/fit`

[Here ](https://github.com/tensorflow/tensorboard/blob/master/docs/r2/get_started.ipynb) the official colab notebook and the [repo ](https://github.com/tensorflow/tensorboard/tree/master/docs/r2) on github

New TFv2.0 alpha release:

CPU
`!pip install -q tensorflow==2.0.0-alpha0`
GPU
`!pip install -q tensorflow-gpu==2.0.0-alpha0`

**Comment by pankudo** [comment]
Thank you. It works nicely 🥇

**Comment by simpleParadox** [comment]
Solved. Thanks!
